/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:0f8c3def-3a14-456e-b435-de0fa9021d81",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_92dgZChkR",
    "aws_user_pools_web_client_id": "6ffgm2l0d18sbbbpigis8v8l17",
    "oauth": {}
};


export default awsmobile;
